### ISSUE TITLE
Crash on first load with MultiMC

### ISSUE THREAD

**Issue by igoutta** [sor1n/Jewelrycraft#14]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 5/11/15 5:07 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: darkknight.jewelrycraft.JewelrycraftMod
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:206)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: darkknight.jewelrycraft.JewelrycraftMod
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
    ... 18 more
Caused by: java.lang.UnsupportedClassVersionError: darkknight/jewelrycraft/JewelrycraftMod : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 46 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_75, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 255826432 bytes (243 MB) / 510066688 bytes (486 MB) up to 1020067840 bytes (972 MB)
    JVM Flags: 19 total; -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc -XX:-UseFastAccessorMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m -XX:PermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.141.1403 Minecraft Forge 10.13.3.1403 Optifine OptiFine_1.7.10_HD_U_B7 47 mods loaded, 47 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.10.141.1403} [Forge Mod Loader](forge-1.7.10-10.13.3.1403-1.7.10-universal.jar) Unloaded->Constructed
    Forge{10.13.3.1403} [Minecraft Forge](forge-1.7.10-10.13.3.1403-1.7.10-universal.jar) Unloaded->Constructed
    CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.0.4.106} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.106-universal.jar) Unloaded->Constructed
    VeinMiner_coremod{0.27.1_build.unknown} [Core mod](minecraft.jar) Unloaded->Constructed
    jewelrycraft2{1.0.9} [Jewelrycraft 2]([1.7.10] Jewelrycraft2-1.0.9-universal.jar) Unloaded->Errored
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed
    deconstruction{2.2.5} [The Deconstruction Mod]([MC1.7.10]deconstruction[v2.2.5].jar) Unloaded->Constructed
    AdvancedHUD{Version [0.1.8] for 1.7.10} [AdvancedHUD](AdvancedHUD[0.1.8].jar) Unloaded->Constructed
    adventurebackpack{1.7.10-0.8b} [Adventure Backpack](adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed
    attainedDrops{1.3} [Attained Drops](AttainedDrops-1.7.10-1.3.jar) Unloaded->Constructed
    atum{0.6} [Atum](Atum-1.7.10-0.6.60.jar) Unloaded->Constructed
    ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed
    chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) Unloaded->Constructed
    claydolls{0.9} [claydolls](Clay Dolls Mod V0.9-1.7.10.jar) Unloaded->Constructed
    colourfulportalsmod{1.4.3} [Colourful Portals](ColourfulPortals-1.4.3.jar) Unloaded->Constructed
    CosmeticArmor{1.0.5} [Cosmetic Armor](CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) Unloaded->Constructed
    DLDungeonsJBG{1.7.5} [Doomlike Dungeons](DoomlikeDungeons-1.7.5-MC1.7.10.jar) Unloaded->Constructed
    dungeonpack{1.7.10-1.0} [Dungeon Pack](dungeonpack-1.7.10-1.0.jar) Unloaded->Constructed
    eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed
    EnderIO{1.7.10-2.2.8.367} [Ender IO](EnderIO-1.7.10-2.2.8.367.jar) Unloaded->Constructed
    EnderZoo{1.7.10-1.0.11.28} [Ender Zoo](EnderZoo-1.7.10-1.0.11.28.jar) Unloaded->Constructed
    extfar{1.7.10-4.0} [Extended Farming](extfar-1.7.10-4.0.jar) Unloaded->Constructed
    FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) Unloaded->Constructed
    fossil{1.7.10 Build 7.1.0} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.1.jar) Unloaded->Constructed
    GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3](GrimoireOfGaia3-1.7.10-1.0.9.jar) Unloaded->Constructed
    HelpFixer{1.0.7} [HelpFixer](HelpFixer-1.0.7.jar) Unloaded->Constructed
    InventoryPets{1.1.1} [Inventory Pets](inventorypets-1.7.10-1.1.1.jar) Unloaded->Constructed
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed
    keysoverhaul{1.0} [Key Bindings Overhaul](KeyBindingsOverhaul-LATEST-1.7.10.jar) Unloaded->Constructed
    LotsOfFood{1.7.10} [Lots of Food](Lots of Food-1.7.10 v7.jar) Unloaded->Constructed
    recipemod{0.2} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.2%281.7.10%29.jar) Unloaded->Constructed
    quantumflux{1.1.0} [QuantumFlux](QuantumFlux-1.1.0.jar) Unloaded->Constructed
    shadowworld{1.3.3} [Shadow World](shadowworld-1.3.3.jar) Unloaded->Constructed
    soundfilters{0.8_for_1.7.X} [Sound Filters](SoundFilters-0.8_for_1.7.X.jar) Unloaded->Constructed
    RioVII{v1.1.4} [The Mists of RioV II](The Mists of RioV II - v1.1.4.jar) Unloaded->Constructed
    erebus{0.2a} [Erebus](TheErebus-0.2b.jar) Unloaded->Constructed
    Torcherino{1.9s} [Torcherino](Torcherino-1.7.10-1.9s.jar) Unloaded->Constructed
    TragicMC{2.43.2375 Beta} [TragicMC 2](TragicMC2-1.7.10-2.43.2375.jar) Unloaded->Constructed
    TwilightForest{2.3.5} [The Twilight Forest](twilightforest-1.7.10-2.3.5.jar) Unloaded->Constructed
    VeinMiner{0.27.1_build.unknown} [Vein Miner](VeinMiner-1.7.10_0.27.1.unknown.jar) Unloaded->Constructed
    VeinMinerModSupport{0.27.1_build.unknown} [Mod Support](VeinMiner-1.7.10_0.27.1.unknown.jar) Unloaded->Constructed
    VersionChecker{1.1.8} [Version Checker](VersionChecker-1.1.8.jar) Unloaded->Constructed
    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) Unloaded->Constructed
    WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) Unloaded->Constructed
    XaeroMinimap{1.4.5} [Xaero's Minimap](xaeros_minimap_v1.4.5_1.7.10_Forge.jar) Unloaded->Constructed

**Comment by sor1n** [comment]
I looked at this and seriously have no idea as to what could be causing it. The error claims the file JewelrycraftMod is missing, which is false, because if it were true everybody would be having the same issue.

**Comment by igoutta** [comment]
Why the fml load _darkknight.jewelrycraft.JewelrycraftMod_ but the class have only this 
_package darkknight.jewelrycraft;_

**Comment by sor1n** [comment]
Oh wow, I think I might know the problem. You should probably have forge installed, nobody uses FML anymore. Dunno if that really is the problem, but please try it.

**Comment by igoutta** [comment]
I have Forge installed (1403), I did an experiment: replace the class of 1.0.9 with the old 1.0.8, but the problem still remains, now I know the problem it's in the new code. I'm using the 1.0.8 (laggy) and works perfectly.

**Comment by sor1n** [comment]
Can you try it with the curse launcher or normal Minecraft launcher and tell me if it does the same thing? Because I tested it with those and it should. I have also tested using MultiMc and it worked just fine. I had created a new instanced with same forge version as you and added my mod and everything was fine. I assume the problem relies on another mod, not mine.

Note: I am pretty sure you aren't supposed to have both FML AND Forge installed at the same time. Please remove FML and try again.

**Comment by pau101** [comment]
Sor1n, it looks like you built the mod for Java 8, while igoutta is running Java 7 from MultiMC, which doesn't automatically use Java 8 like the vanilla launcher.

**Comment by igoutta** [comment]
Interesting.

**Comment by sor1n** [comment]
Ok then, so update to Java 8, please :3 Also I thought Java 7 is compatible with Java 8, but I guess not.

**Comment by sor1n** [comment]
I'm going to close the issue if Java 7 was the problem. Just use Java 8 and everything will be fine.

**Comment by igoutta** [comment]
Last comment: Edit in curseforge the avalaible versions of Java for the file, that's was the first problem in fact.

**Comment by sor1n** [comment]
Ok ;)
